spring:
  application:
    name: create-web-app
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate: 
      boot:
        allow_jdbc_metadata_access: true
      ddl-auto: create-drop
    properties:
        format_sql: true

server:
  port: ${APP_PORT}

logging:
  level:
    org:
      springframework: INFO
